### Numpy Operation

#### What is Numpy ?

#### Numpy is primarily used for scientific numberic computing .It is a Python Library that supports Multidimensional array object i.e can be used for fast operation . We can numerous task using numpy such as searching , sorting , basic Linear Algebra , Matrix , basic statistics operation , random simulation , etc.                                                                                                                                                          NumPy arrays have a fixed size at creation, unlike Python lists which can grow dynamically. Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the homogeneous data type, and thus will be the same size in memory . A plethora of Scientific and Mathematic Python Packages are using Numpy

In [3]:
import numpy as np

In [4]:
##1d/Single Dimensional Array
arr = np.array([2,4,6,8])

In [5]:
arr

array([2, 4, 6, 8])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
##2d and 3d array
arr1 = np.array([[1,2],[3,4],[5,6],[7,8]])

In [8]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [17]:
print(type(arr3))

<class 'numpy.ndarray'>


In [21]:
#dtype
arr4 =np.array([1,2,3,4,5],dtype = float)

In [22]:
arr4

array([1., 2., 3., 4., 5.])

In [25]:
arr5 = np.array([1,0,1,0],dtype = complex)

In [26]:
arr5

array([1.+0.j, 0.+0.j, 1.+0.j, 0.+0.j])

In [28]:
#arange
arr6 = np.arange(1,12)

In [29]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
#with reshape
arr7 = np.arange(12).reshape(3,4)

In [82]:
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
#np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
#np.zeros
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
#np.random
np.random.random((4,3))

array([[0.32085484, 0.28186823, 0.46992648],
       [0.45884991, 0.61291481, 0.50171126],
       [0.1775864 , 0.62460219, 0.97455037],
       [0.42100245, 0.7465111 , 0.05377869]])

### Numpy Attributes

In [51]:
##Creating array
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [54]:
#ndims
a1.ndim

1

In [55]:
a2.ndim

2

In [56]:
a3.ndim

3

In [57]:
#shape
a1.shape

(10,)

In [58]:
a2.shape

(3, 4)

In [59]:
a3.shape

(2, 2, 2)

In [60]:
#size
a1.size

10

In [61]:
a2.size

12

In [62]:
a3.size

8

In [63]:
#itemsize
a1.itemsize

4

In [64]:
a2.itemsize

8

In [65]:
a3.itemsize

4

In [67]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [77]:
#astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

In [78]:
print(a3.dtype)

int32


In [75]:
print(a2.dtype)

float64


In [76]:
print(a1.dtype)

int32


In [93]:
array1 = np.arange(12).reshape(4,3)
array2 = np.arange(12,24).reshape(4,3)

In [94]:
array1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
array2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [96]:
#Scaler operation : In scaler we have to perform operation by using different value it could be anything 
#arithemetic
#relational
array1 ** 2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]], dtype=int32)

In [97]:
array1 > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [98]:
array1 +2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [99]:
#relational
array1 == 10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [100]:
#vector operation: In vector we have to perform all the operation on the array itself
array1 * array2

array([[  0,  13,  28],
       [ 45,  64,  85],
       [108, 133, 160],
       [189, 220, 253]])

In [101]:
array1 ** array2

array([[          0,           1,       16384],
       [   14348907,           0, -1564725563],
       [ 1159987200,   442181591,           0],
       [ 1914644777, -1304428544,  -122979837]], dtype=int32)

In [102]:
print(np.__version__)

1.19.2


In [106]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shrutika/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shrutika/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shrutika/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shrutika/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shrutika/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shrutika/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shrutika/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shrutika/anaconda3\\Library\\include']


### Numpy Array Function

In [107]:
array3 = np.random.random((3,3))
array3 = np.round(array3*100)
array3

array([[72., 58., 72.],
       [25., 89., 72.],
       [52., 45., 99.]])

In [113]:
#min/max/sum/product
#0->column and 1 -> rows
np.max(array3 , axis = 1)

array([72., 89., 99.])

In [110]:
np.min(array3)

25.0

In [111]:
np.sum(array3)

584.0

In [112]:
np.product(array3)

1.1158518818304e+16

In [115]:
#mean,median,std,var
np.mean(array3 , axis = 1)

array([67.33333333, 62.        , 65.33333333])

In [116]:
np.median(array3 , axis = 0)

array([52., 58., 72.])

In [117]:
np.std(array3,axis = 1)

array([ 6.59966329, 27.06781607, 23.97684068])

In [118]:
np.var(array3 , axis = 0)

array([370.88888889, 340.66666667, 162.        ])

In [119]:
#Trignometry function
np.sin(array3)

array([[ 0.25382336,  0.99287265,  0.25382336],
       [-0.13235175,  0.86006941,  0.25382336],
       [ 0.98662759,  0.85090352, -0.99920683]])

In [120]:
np.tan(array3)

array([[ -0.26241738,   8.33085685,  -0.26241738],
       [ -0.13352641,   1.68582537,  -0.26241738],
       [ -6.05327238,   1.61977519, -25.09253498]])

In [129]:
array4 = np.arange(12).reshape(3,4)
array5 = np.arange(12,24).reshape(4,3)

In [130]:
array4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
array5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [132]:
##dot product i.e i*j == j* i
np.dot(array4,array5)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [133]:
np.log(array4)

<ipython-input-133-217364b9d165>:1: RuntimeWarning: divide by zero encountered in log
  np.log(array4)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [134]:
np.exp(array4)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])